// Pre-defined starter designs for the invitation card. Each is a complete pdfme
// Template (A6, 105×148 mm, no margin). Every preset MUST include a `guestName`
// text field (locked, filled per guest) and a `qr` qrcode field (required on save);
// `eventTitle` / `eventDate` auto-fill from the event when those field names are kept.

type Schema = Record<string, any>
type Template = {
  basePdf: { width: number; height: number; padding: [number, number, number, number] }
  schemas: Schema[][]
}
export type CardTemplatePreset = { id: string; name: string; template: Template }

const A6 = { width: 105, height: 148, padding: [0, 0, 0, 0] as [number, number, number, number] }
const QR_SAMPLE = 'https://example.com'

export const CARD_TEMPLATES: CardTemplatePreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    template: {
      basePdf: A6,
      schemas: [
        [
          {
            name: 'eyebrow',
            type: 'text',
            content: "YOU'RE INVITED",
            position: { x: 8, y: 16 },
            width: 89,
            height: 6,
            fontSize: 9,
            alignment: 'center',
            characterSpacing: 2,
            fontColor: '#9ca3af',
          },
          {
            name: 'eventTitle',
            type: 'text',
            content: 'Event Title',
            position: { x: 8, y: 26 },
            width: 89,
            height: 16,
            fontSize: 22,
            alignment: 'center',
            fontColor: '#111827',
          },
          {
            name: 'guestName',
            type: 'text',
            content: 'Guest Name',
            position: { x: 8, y: 48 },
            width: 89,
            height: 8,
            fontSize: 13,
            alignment: 'center',
            fontColor: '#374151',
          },
          {
            name: 'eventDate',
            type: 'text',
            content: 'Event date',
            position: { x: 8, y: 58 },
            width: 89,
            height: 6,
            fontSize: 9,
            alignment: 'center',
            fontColor: '#9ca3af',
          },
          {
            name: 'qr',
            type: 'qrcode',
            content: QR_SAMPLE,
            position: { x: 37.5, y: 74 },
            width: 30,
            height: 30,
            backgroundColor: '#ffffff',
            barColor: '#000000',
          },
          {
            name: 'qrLabel',
            type: 'text',
            content: 'Scan at the entrance',
            position: { x: 8, y: 108 },
            width: 89,
            height: 6,
            fontSize: 9,
            alignment: 'center',
            fontColor: '#9ca3af',
          },
        ],
      ],
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    template: {
      basePdf: A6,
      schemas: [
        [
          {
            name: 'frame',
            type: 'rectangle',
            position: { x: 6, y: 6 },
            width: 93,
            height: 136,
            color: '',
            borderColor: '#b08d57',
            borderWidth: 0.8,
            radius: 2,
          },
          {
            name: 'eyebrow',
            type: 'text',
            content: 'TOGETHER WITH JOY',
            position: { x: 12, y: 20 },
            width: 81,
            height: 6,
            fontSize: 8,
            alignment: 'center',
            characterSpacing: 3,
            fontColor: '#b08d57',
          },
          {
            name: 'eventTitle',
            type: 'text',
            content: 'Event Title',
            position: { x: 12, y: 30 },
            width: 81,
            height: 18,
            fontSize: 24,
            alignment: 'center',
            fontColor: '#1f2937',
          },
          {
            name: 'divider',
            type: 'line',
            position: { x: 42, y: 53 },
            width: 21,
            height: 0.4,
            color: '#b08d57',
          },
          {
            name: 'guestName',
            type: 'text',
            content: 'Guest Name',
            position: { x: 12, y: 59 },
            width: 81,
            height: 8,
            fontSize: 13,
            alignment: 'center',
            fontColor: '#374151',
          },
          {
            name: 'eventDate',
            type: 'text',
            content: 'Event date',
            position: { x: 12, y: 69 },
            width: 81,
            height: 6,
            fontSize: 9,
            alignment: 'center',
            fontColor: '#9ca3af',
          },
          {
            name: 'qr',
            type: 'qrcode',
            content: QR_SAMPLE,
            position: { x: 40, y: 85 },
            width: 25,
            height: 25,
            backgroundColor: '#ffffff',
            barColor: '#1f2937',
          },
          {
            name: 'qrLabel',
            type: 'text',
            content: 'Present this code at the door',
            position: { x: 12, y: 115 },
            width: 81,
            height: 6,
            fontSize: 8,
            alignment: 'center',
            fontColor: '#9ca3af',
          },
        ],
      ],
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    template: {
      basePdf: A6,
      schemas: [
        [
          {
            name: 'topline',
            type: 'line',
            position: { x: 12, y: 18 },
            width: 24,
            height: 0.6,
            color: '#111827',
          },
          {
            name: 'eventTitle',
            type: 'text',
            content: 'Event Title',
            position: { x: 12, y: 26 },
            width: 81,
            height: 24,
            fontSize: 24,
            alignment: 'left',
            fontColor: '#111827',
          },
          {
            name: 'guestName',
            type: 'text',
            content: 'Guest Name',
            position: { x: 12, y: 62 },
            width: 70,
            height: 8,
            fontSize: 13,
            alignment: 'left',
            fontColor: '#374151',
          },
          {
            name: 'eventDate',
            type: 'text',
            content: 'Event date',
            position: { x: 12, y: 72 },
            width: 81,
            height: 6,
            fontSize: 10,
            alignment: 'left',
            fontColor: '#9ca3af',
          },
          {
            name: 'qr',
            type: 'qrcode',
            content: QR_SAMPLE,
            position: { x: 70, y: 110 },
            width: 24,
            height: 24,
            backgroundColor: '#ffffff',
            barColor: '#000000',
          },
          {
            name: 'qrLabel',
            type: 'text',
            content: 'Scan to enter',
            position: { x: 12, y: 120 },
            width: 50,
            height: 6,
            fontSize: 9,
            alignment: 'left',
            fontColor: '#9ca3af',
          },
        ],
      ],
    },
  },
  {
    id: 'bold',
    name: 'Bold',
    template: {
      basePdf: A6,
      schemas: [
        [
          {
            name: 'band',
            type: 'rectangle',
            position: { x: 0, y: 0 },
            width: 105,
            height: 52,
            color: '#6d28d9',
            borderWidth: 0,
            borderColor: '#6d28d9',
            radius: 0,
          },
          {
            name: 'eyebrow',
            type: 'text',
            content: "YOU'RE INVITED",
            position: { x: 8, y: 16 },
            width: 89,
            height: 6,
            fontSize: 9,
            alignment: 'center',
            characterSpacing: 2,
            fontColor: '#ede9fe',
          },
          {
            name: 'eventTitle',
            type: 'text',
            content: 'Event Title',
            position: { x: 8, y: 24 },
            width: 89,
            height: 18,
            fontSize: 22,
            alignment: 'center',
            fontColor: '#ffffff',
          },
          {
            name: 'guestName',
            type: 'text',
            content: 'Guest Name',
            position: { x: 8, y: 64 },
            width: 89,
            height: 8,
            fontSize: 14,
            alignment: 'center',
            fontColor: '#111827',
          },
          {
            name: 'eventDate',
            type: 'text',
            content: 'Event date',
            position: { x: 8, y: 74 },
            width: 89,
            height: 6,
            fontSize: 10,
            alignment: 'center',
            fontColor: '#6b7280',
          },
          {
            name: 'qr',
            type: 'qrcode',
            content: QR_SAMPLE,
            position: { x: 39.5, y: 88 },
            width: 26,
            height: 26,
            backgroundColor: '#ffffff',
            barColor: '#111827',
          },
          {
            name: 'qrLabel',
            type: 'text',
            content: 'Scan at the entrance',
            position: { x: 8, y: 118 },
            width: 89,
            height: 6,
            fontSize: 9,
            alignment: 'center',
            fontColor: '#9ca3af',
          },
        ],
      ],
    },
  },
]
